#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm test || echo 'No tests found, skipping.'
branch=main; if [ "" = "main" ]; then echo 'Direct push to main is not allowed. Please use a PR.'; exit 1; fi
